name: SitAnyware
version: '1.0'
main: org.ZenMatrix.sitAnyware.SitAnyware
api-version: '1.21'
commands:
  Sit:
    Description: "Sit Down"
    Usage: "/sit"
  Sleep:
    Description: "Sleeps Anyware"
    Usage: "/sleep"

